/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stockbot;


import org.json.JSONObject;
import org.jsoup.Jsoup;
import org.jsoup.nodes.Document;
import org.jsoup.nodes.Element;

import java.io.IOException;

public class Stock {
    public static Integer getStockPriceWithQuery(String stockName) {
        StockInfo stockInfo = getStockInfo(stockName);
        if (stockInfo == null) {
            return null;
        }
        return getStockPrice(stockInfo.code);
    }

    public static Integer getStockPrice(String code) {
        try {
            Document document = Jsoup.connect("https://polling.finance.naver.com/api/realtime?query=SERVICE_ITEM%3A" + code)
                    .get();
            JSONObject jsonObject = new JSONObject(document.text());
            int price = jsonObject.getJSONObject("result")
                    .getJSONArray("areas")
                    .getJSONObject(0)
                    .getJSONArray("datas")
                    .getJSONObject(0)
                    .getInt("nv");
            return price;
        } catch (IOException e) {
            e.printStackTrace();
        }

        return null;
    }

    public static StockInfo getStockInfo(String stockName) {
        try {
            Document document = Jsoup.connect("https://www.google.com/search?q=%EC%A3%BC%EA%B0%80 " + stockName)
                    .get();
            Element nameElement = document.select("div[class=oPhL2e]").first();
            if (nameElement == null) {
                return null;
            }
            String name = nameElement.text();
            Element codeElement = document.select("div[class=HfMth]").first();
            String rawCode = codeElement.text();
            String code = null;
            String market = null;
            if (rawCode.startsWith("KRX: ")) {
                code = rawCode.substring("KRX: ".length());
                market = StockInfo.MARKET_KOSPI;
            } else if (rawCode.startsWith("KOSDAQ: ")) {
                code = rawCode.substring("KOSDAQ: ".length());
                market = StockInfo.MARKET_KOSDAQ;
            } else {
                assert false;
            }

            return new StockInfo(name, market, code);
        } catch (IOException e) {
            e.printStackTrace();
        }

        return null;
    }
}
