/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package stockbot;

public class StockInfo {
    public static final String MARKET_KOSPI = "kospi";
    public static final String MARKET_KOSDAQ = "kosdaq";
    public String stockName;
    public String market;
    public String code;

    public StockInfo(String stockName, String market, String code) {
        this.stockName = stockName;
        this.market = market;
        this.code = code;
    }
}
